# Generated by Django 5.2 on 2025-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("it_owner", "IT Owner"),
                    ("site_admin", "Site Admin"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
