# Generated by Django 4.2.11 on 2025-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="browser_info",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
