# Generated by Django 4.2.20 on 2025-04-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleCompletion',
        ),
    ]
