# Generated by Django 5.2 on 2025-04-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_modulecompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingModule',
        ),
    ]
