# Generated by Django 4.2.20 on 2025-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courseassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phishingtest',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='phishingtest',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phishingtest',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingtest',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phishingtest',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phishingtest',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtest',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
