# Generated by Django 5.2 on 2025-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoPhishGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('targets', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoPhishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoPhishUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('role', models.JSONField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
