# Generated by Django 5.2 on 2025-05-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gophishgroups_gophishtemplate_gophishusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoPhishGroups',
        ),
        migrations.DeleteModel(
            name='GoPhishTemplate',
        ),
        migrations.DeleteModel(
            name='GoPhishUsers',
        ),
    ]
