name: PhishLearn CI/CD

on:
  push:
    branches: [ main, dev, leileBranch ]
  pull_request:
    branches: [ main, dev, leileBranch ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up environment variables
      run: |
        cat << EOF > .env
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        EMAIL_HOST=${{ secrets.EMAIL_HOST }}
        EMAIL_PORT=${{ secrets.EMAIL_PORT }}
        EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}
        EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
        DEBUG=True
        DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
        GOPHISH_API_URL=http://localhost:3333
        GOPHISH_API_KEY=${{ secrets.GOPHISH_API_KEY }}
        EOF

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Check if docker-compose.yml exists
      working-directory: ./phishlearn
      run: |
        echo "Working directory: $(pwd)"
        echo "Subdirectories:"
        ls -la
       
    
    - name: Build Docker images
      working-directory: ./phishlearn
      run: docker compose build

    - name: Set up environment variables for Docker Compose
      working-directory: ./phishlearn
      run: |
        mkdir -p phishlearn
        cat << EOF > .env
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        EMAIL_HOST=${{ secrets.EMAIL_HOST }}
        EMAIL_PORT=${{ secrets.EMAIL_PORT }}
        EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}
        EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
        DEBUG=True
        DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
        GOPHISH_API_URL=http://localhost:3333
        GOPHISH_API_KEY=${{ secrets.GOPHISH_API_KEY }}
        EOF
    
        echo "Created.env for Docker Compose"
         echo "----------------------------------------------"
         cat .env
         echo "----------------------------------------------"
    
    - name: Start Docker containers
      working-directory: ./phishlearn
      run: docker compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to initialize..."
        sleep 15
    
    - name: Run migrations
      working-directory: ./phishlearn
      run: docker-compose exec -T phishlearn python manage.py migrate
    
    - name: Create admin user
      working-directory: ./phishlearn
      run: |
        docker-compose exec -T phishlearn python -c "
        import os
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'phishlearn.settings')
        import django
        django.setup()
        from django.contrib.auth.models import User
        if not User.objects.filter(username='faculty').exists():
            User.objects.create_superuser('faculty', 'admin@example.com', 'faculty')
            print('Admin user created')
        else:
            print('Admin user already exists')
        "
    
    - name: Run tests
      working-directory: ./phishlearn
      run: docker-compose exec -T phishlearn python manage.py test
    
    - name: Check API endpoint
      working-directory: ./phishlearn
      run: |
        echo "Checking API connection endpoint..."
        curl --retry 5 --retry-delay 3 -s -o /dev/null -w "%{http_code}" http://localhost:8000/api/connection/ | grep 200 || echo "API endpoint not available"
    
    - name: Collect static files
      working-directory: ./phishlearn
      run: docker-compose exec -T phishlearn python manage.py collectstatic --noinput
    
    - name: Stop Docker containers
      working-directory: ./phishlearn
      run: docker-compose down

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up environment variables for production
      run: |
        cat << EOF > .env
        DJANGO_SECRET_KEY=${{ secrets.PROD_DJANGO_SECRET_KEY }}
        POSTGRES_USER=${{ secrets.PROD_POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.PROD_POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.PROD_POSTGRES_DB }}
        DATABASE_HOST=${{ secrets.PROD_DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.PROD_DATABASE_PORT }}
        SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.PROD_SUPABASE_KEY }}
        EMAIL_HOST=${{ secrets.PROD_EMAIL_HOST }}
        EMAIL_PORT=${{ secrets.PROD_EMAIL_PORT }}
        EMAIL_USE_TLS=${{ secrets.PROD_EMAIL_USE_TLS }}
        EMAIL_HOST_USER=${{ secrets.PROD_EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD=${{ secrets.PROD_EMAIL_HOST_PASSWORD }}
        DEBUG=False
        DJANGO_ALLOWED_HOSTS=${{ secrets.PROD_ALLOWED_HOSTS }}
        GOPHISH_API_URL=${{ secrets.PROD_GOPHISH_API_URL }}
        GOPHISH_API_KEY=${{ secrets.PROD_GOPHISH_API_KEY }}
        EOF
    
    # Uncomment one of the following deployment options based on your hosting choice:
    
    # Option 1: Deploy to AWS Elastic Beanstalk
    # - name: Deploy to AWS Elastic Beanstalk
    #   uses: einaregilsson/beanstalk-deploy@v21
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     application_name: ${{ secrets.EB_APPLICATION_NAME }}
    #     environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
    #     version_label: phishlearn-${{ github.sha }}
    #     region: ${{ secrets.AWS_REGION }}
    #     deployment_package: deploy.zip
    
    # Option 2: Deploy to Digital Ocean App Platform
    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    # - name: Build and push to DO Container Registry
    #   run: |
    #     doctl registry login
    #     docker build -t registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/phishlearn:${GITHUB_SHA::7} .
    #     docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/phishlearn:${GITHUB_SHA::7}
    
    # Option 3: Deploy to VPS via SSH
    # - name: Deploy to VPS
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /path/to/project
    #       git pull origin main
    #       cp /path/to/production/.env .env
    #       docker-compose down
    #       docker-compose up -d --build
    
    - name: Placeholder for deployment
      run: echo "Select and configure one of the deployment options based on your hosting preferences"
